import React from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta name="description" content="Nayana's portfolio: all my work experience, projects, hobbies, and more!" />
        <meta name="keywords" content="HTML, CSS, Javascript, React, portfolio, resume, Nayana" />
        <meta name="author" content="Nayana Agrawal" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>{children}</body>
    </html>
              )
}
